# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  application:
    name: messagingApp
  jackson:
    serialization.write_dates_as_timestamps: false
server:
  session:
    cookie:
      http-only: true

# ===================================================================
# Specific properties
# ===================================================================
